name: Deploy Static Website with Docker

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.balamurugan2025 }}
        password: ${{ secrets.Kuben@4110 }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: balamurugan2025/static-web:latest

    # Optional: Deploy to a server via SSH
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.65.0.31.178 }}
        username: ${{ secrets.ubuntu }}
        key: ${{ secrets.b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
             QyNTUxOQAAACAYCHBD5qnSYIX7qqZB95QAd3lz9oXcQ2vPcWbTHrIewAAAAKAOH1hhDh9Y
             YQAAAAtzc2gtZWQyNTUxOQAAACAYCHBD5qnSYIX7qqZB95QAd3lz9oXcQ2vPcWbTHrIewA
             AAAEBmI7EkX6uj/pMu73UfQbwC4FXM3TwucI2Dlo5AyNGfxRgIcEPmqdJghfuqpkH3lAB3
             eXP2hdxDa89xZtMesh7AAAAAHGJhbGFtdXJ1Z2Fua3ViZW4yMUBnbWFpbC5jb20B }}
        script: |
          docker pull your-dockerhub-username/static-web:latest
          docker stop static-web || true
          docker rm static-web || true
          docker run -d --name static-web -p 80:80 your-dockerhub-username/static-web:latest


